# Generated by Django 6.0.3 on 2026-03-30 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(default='有氧', max_length=50)),
                ('fit_goal', models.CharField(choices=[('lose_weight', '减脂'), ('gain_muscle', '增肌'), ('maintain', '保持健康')], default='lose_weight', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('calories', models.PositiveIntegerField(default=200)),
                ('difficulty', models.CharField(default='中等', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fit_goal', models.CharField(choices=[('lose_weight', '减脂'), ('gain_muscle', '增肌'), ('maintain', '保持健康')], default='lose_weight', max_length=20)),
                ('calories', models.PositiveIntegerField(default=300)),
                ('protein', models.FloatField(default=20)),
                ('preference_tag', models.CharField(default='清淡', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(auto_now_add=True)),
                ('exercise_text', models.TextField()),
                ('diet_text', models.TextField()),
                ('suggestion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_type', models.CharField(choices=[('exercise', '运动打卡'), ('diet', '饮食打卡'), ('weight', '体重打卡')], max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('feeling', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.recommendationplan')),
            ],
        ),
    ]
