# Generated by Django 6.0.3 on 2026-03-30 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='体重 kg')),
                ('body_fat', models.FloatField(blank=True, help_text='体脂率 %', null=True)),
                ('bmi', models.FloatField(default=0)),
                ('bmr', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('record_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
