# Generated by Django 6.0.3 on 2026-03-30 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10)),
                ('height', models.FloatField(default=170, help_text='身高，单位 cm')),
                ('current_weight', models.FloatField(default=60, help_text='当前体重，单位 kg')),
                ('target_weight', models.FloatField(default=55, help_text='目标体重，单位 kg')),
                ('goal_type', models.CharField(choices=[('lose_weight', '减脂'), ('gain_muscle', '增肌'), ('maintain', '保持健康')], default='lose_weight', max_length=20)),
                ('exercise_preference', models.CharField(blank=True, default='跑步,快走', max_length=100)),
                ('diet_preference', models.CharField(blank=True, default='高蛋白,清淡', max_length=100)),
                ('dislike_items', models.CharField(blank=True, default='油炸食品', max_length=100)),
                ('available_time', models.CharField(blank=True, default='晚上 30 分钟', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
